### ISSUE TITLE
Trailers won't play if filename contains a comma

### ISSUE THREAD

**Issue by gnoling** [jurialmunkey/skin.horizon#16]
Title says it all, if the filename contains a comma the trailer failures to play, an example is:

`/videos/Movies (OWNED)/Hitman's Bodyguard, The (2017)/The Hitman's Bodyguard-trailer.mov`

Ends up with:

`libnfs error: NFS: Lookup of /videos/Movies (OWNED)/Hitman's Bodyguard failed with NFS3ERR_NOENT(-2)`

**Comment by jurialmunkey** [comment]
Thanks for pointing this bug out :)

Instead of using quotes around the infolabel, the correct way to deal with escaping characters is to use $ESCINFO instead of $INFO

See this commit: https://github.com/jurialmunkey/skin.horizon/commit/54eaede56819ae17381b188159a50487ab0743de

Please confirm that it is now working.

**Comment by gnoling** [comment]
Yup, that does the trick.

**Comment by jurialmunkey** [comment]
Excellent! Made it just in time for my PR for the next update on official repo. 😃
