### ISSUE TITLE
Categories fail to keep separate views & Lock View is Broken

### ISSUE THREAD

**Issue by trumblejoe** [jurialmunkey/skin.horizon#7]
I have a recently-added category within Movies, and if I set a LoveFilm view, and then leave the category, enter my Movie library and set a new view, my Categories view is also changed.

This happens whether Lock View is selected or not. Also, Lock View appears to be broken, I can lock it, go to the top menu item to change a view, press 'Enter', and it will unlock, pressing enter again changes the view. I tested this multiple times.

Current as of Commit e0c19f9e5ec1e26669ed47786894d1972f4c5597

**Comment by jurialmunkey** [comment]
Lock view doesn't stop you from changing the view. It sets that view for all content of that type (e.g. if you lock a view at the episode level of the library, then it will force that view to be set whenever the content type is episodes). Use Kiosk Mode if you want to prevent others from changing views altogether (Skin Settings > Misc > Kiosk Mode).

Regarding your first problem, either it is because you misunderstand what lock view does and are locking the view for that content type or it is simply to do with how kodi core sets viewtypes in general (kodi will try to set the same viewtype id for similar content).
